import type { UserFlow, UserFlowStep, LoadConfig, LoadStage } from './types';

/**
 * Generates k6 JavaScript test scripts from user flow definitions.
 *
 * The produced script is valid k6 ES-module syntax and can be executed
 * directly with `k6 run <script.js>`.
 */
export class K6Generator {
  /**
   * Generate a complete k6 script string from the supplied flows and config.
   *
   * @param flows  - One or more user flows to include in the script.
   * @param config - Load configuration (VUs, duration, stages, thresholds…).
   * @returns      A string containing the complete k6 JavaScript script.
   */
  generate(flows: UserFlow[], config: LoadConfig): string {
    if (flows.length === 0) {
      throw new Error('At least one UserFlow must be provided to generate a k6 script.');
    }

    const parts: string[] = [
      this.generateImports(),
      '',
      this.generateOptions(config),
      '',
      ...flows.map((flow) => this.generateFlowFunction(flow, config)),
      this.generateDefaultFunction(flows),
    ];

    return parts.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private – script sections
  // ---------------------------------------------------------------------------

  private generateImports(): string {
    return [
      "import http from 'k6/http';",
      "import { sleep, check } from 'k6';",
    ].join('\n');
  }

  private generateOptions(config: LoadConfig): string {
    const stages = this.resolveStages(config);
    const p95Limit = config.thresholds?.httpReqDurationP95 ?? 2000;
    const failedLimit = config.thresholds?.httpReqFailedRate ?? 0.1;

    const optionLines: string[] = [
      '/** k6 test options – generated by @semkiest/agent-load */',
      'export const options = {',
      "  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(50)', 'p(90)', 'p(95)', 'p(99)'],",
    ];

    if (stages.length > 0) {
      optionLines.push('  stages: [');
      for (const stage of stages) {
        optionLines.push(`    { duration: '${stage.duration}', target: ${stage.target} },`);
      }
      optionLines.push('  ],');
    } else {
      const vus = config.virtualUsers ?? 10;
      const duration = config.duration ?? '30s';
      optionLines.push(`  vus: ${vus},`);
      optionLines.push(`  duration: '${duration}',`);
    }

    optionLines.push('  thresholds: {');
    optionLines.push(`    http_req_duration: ['p(95)<${p95Limit}'],`);
    optionLines.push(`    http_req_failed: ['rate<${failedLimit}'],`);
    optionLines.push('  },');
    optionLines.push('};');

    return optionLines.join('\n');
  }

  /**
   * Resolve the effective stage list from the config.
   * If `stages` is provided it is used as-is.
   * If `rampUp`/`rampDown` are set a three-stage pattern is synthesised.
   * Otherwise an empty array is returned and the `vus`/`duration` path is used.
   */
  private resolveStages(config: LoadConfig): LoadStage[] {
    if (config.stages && config.stages.length > 0) {
      return config.stages;
    }

    if (config.rampUp) {
      const vus = config.virtualUsers ?? 10;
      const steadyDuration = config.duration ?? '30s';
      const rampDown = config.rampDown ?? '10s';

      return [
        { duration: config.rampUp, target: vus },
        { duration: steadyDuration, target: vus },
        { duration: rampDown, target: 0 },
      ];
    }

    return [];
  }

  private generateFlowFunction(flow: UserFlow, config: LoadConfig): string {
    const fnName = this.toValidIdentifier(flow.name);
    const thinkTimeSec = (flow.thinkTime ?? 1000) / 1000;
    const lines: string[] = [`export function ${fnName}() {`];

    for (let i = 0; i < flow.steps.length; i++) {
      const step = flow.steps[i];
      lines.push(...this.generateStep(step, i, config.baseUrl));

      // Insert think-time between steps (but not after the last one)
      if (i < flow.steps.length - 1 && thinkTimeSec > 0) {
        lines.push(`  sleep(${thinkTimeSec});`);
      }
    }

    lines.push('}', '');
    return lines.join('\n');
  }

  private generateStep(
    step: UserFlowStep,
    index: number,
    baseUrl?: string,
  ): string[] {
    const url = this.resolveUrl(step.url, baseUrl);
    const varName = `res${index + 1}`;
    const expectedStatus = step.expectedStatus ?? 200;
    const checkKey = `${step.method} ${step.url} → ${expectedStatus}`;
    const lines: string[] = [];

    const paramsArg = this.buildParamsArg(step);

    switch (step.method) {
      case 'GET':
      case 'DELETE':
        lines.push(`  const ${varName} = http.${step.method.toLowerCase()}('${url}'${paramsArg});`);
        break;
      case 'POST':
      case 'PUT':
      case 'PATCH': {
        const bodyArg = step.body ? `JSON.stringify(${JSON.stringify(step.body)})` : 'null';
        const hasParams = paramsArg.length > 0;
        const headersWithContentType = this.mergeContentTypeHeader(step.headers);
        const fullParams = hasParams
          ? paramsArg
          : `, { headers: ${JSON.stringify(headersWithContentType)} }`;
        lines.push(
          `  const ${varName} = http.${step.method.toLowerCase()}('${url}', ${bodyArg}${fullParams});`,
        );
        break;
      }
    }

    lines.push(`  check(${varName}, {`);
    lines.push(
      `    ${JSON.stringify(checkKey)}: (r) => r.status === ${expectedStatus},`,
    );
    lines.push('  });');

    return lines;
  }

  private buildParamsArg(step: UserFlowStep): string {
    const hasHeaders = step.headers && Object.keys(step.headers).length > 0;
    const hasTags = step.tags && Object.keys(step.tags).length > 0;

    if (!hasHeaders && !hasTags) {
      return '';
    }

    const parts: string[] = [];
    if (hasHeaders) {
      parts.push(`headers: ${JSON.stringify(step.headers)}`);
    }
    if (hasTags) {
      parts.push(`tags: ${JSON.stringify(step.tags)}`);
    }

    return `, { ${parts.join(', ')} }`;
  }

  private mergeContentTypeHeader(
    existing?: Record<string, string>,
  ): Record<string, string> {
    return {
      'Content-Type': 'application/json',
      ...(existing ?? {}),
    };
  }

  private generateDefaultFunction(flows: UserFlow[]): string {
    if (flows.length === 1) {
      const fnName = this.toValidIdentifier(flows[0].name);
      return `export default function () {\n  ${fnName}();\n}\n`;
    }

    // Weighted random selection for multiple flows
    const totalWeight = flows.reduce((sum, f) => sum + (f.weight ?? 1), 0);
    const lines: string[] = [
      'export default function () {',
      `  const rand = Math.random() * ${totalWeight};`,
      '  let cumulative = 0;',
    ];

    for (let i = 0; i < flows.length; i++) {
      const fnName = this.toValidIdentifier(flows[i].name);
      const weight = flows[i].weight ?? 1;
      const isLast = i === flows.length - 1;

      if (isLast) {
        lines.push(`  ${fnName}();`);
      } else {
        lines.push(`  cumulative += ${weight};`);
        lines.push(`  if (rand < cumulative) { ${fnName}(); return; }`);
      }
    }

    lines.push('}', '');
    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Utilities
  // ---------------------------------------------------------------------------

  private resolveUrl(url: string, baseUrl?: string): string {
    if (!baseUrl || url.startsWith('http://') || url.startsWith('https://')) {
      return url;
    }
    const base = baseUrl.replace(/\/$/, '');
    const path = url.startsWith('/') ? url : `/${url}`;
    return `${base}${path}`;
  }

  /**
   * Convert an arbitrary string into a valid JavaScript identifier.
   * Replaces non-alphanumeric characters with underscores and ensures
   * the result doesn't start with a digit.
   */
  private toValidIdentifier(name: string): string {
    const sanitised = name.replace(/[^a-zA-Z0-9_]/g, '_');
    return /^\d/.test(sanitised) ? `flow_${sanitised}` : sanitised;
  }
}
