import type { Severity } from './types';

/**
 * Valid Asana tag colour identifiers.
 * See: https://developers.asana.com/reference/createtag
 */
export type AsanaTagColor =
  | 'dark-pink'
  | 'dark-green'
  | 'dark-blue'
  | 'dark-red'
  | 'dark-teal'
  | 'dark-brown'
  | 'dark-orange'
  | 'dark-purple'
  | 'dark-warm-gray'
  | 'light-pink'
  | 'light-orange'
  | 'light-yellow'
  | 'light-teal'
  | 'light-blue'
  | 'light-purple'
  | 'light-red'
  | 'light-green'
  | 'light-warm-gray'
  | 'none';

/**
 * Internal priority notation used as a prefix in task names and tag names
 * so that Asana tasks can be sorted/filtered even without custom fields.
 */
export type InternalPriority = 'P0' | 'P1' | 'P2' | 'P3';

/**
 * The complete mapping for a given severity level.
 */
export interface SeverityMapping {
  /** Tag name applied to the Asana task */
  tagName: string;
  /** Colour of the severity tag in Asana */
  tagColor: AsanaTagColor;
  /** Short priority notation prepended to task names */
  priority: InternalPriority;
  /** Human-readable description added to the task notes header */
  description: string;
}

/**
 * Maps each SemkiEst severity level to its corresponding Asana representation.
 *
 * - critical → P0, dark-red tag  → immediate action required
 * - high     → P1, dark-orange   → fix in current sprint
 * - medium   → P2, light-yellow  → fix in next sprint
 * - low      → P3, light-green   → fix when capacity allows
 */
export const SEVERITY_MAPPINGS: Readonly<Record<Severity, SeverityMapping>> = {
  critical: {
    tagName: '[BUG] Critical',
    tagColor: 'dark-red',
    priority: 'P0',
    description: 'Critical severity — immediate action required.',
  },
  high: {
    tagName: '[BUG] High',
    tagColor: 'dark-orange',
    priority: 'P1',
    description: 'High severity — should be fixed in the current sprint.',
  },
  medium: {
    tagName: '[BUG] Medium',
    tagColor: 'light-yellow',
    priority: 'P2',
    description: 'Medium severity — fix in the next sprint.',
  },
  low: {
    tagName: '[BUG] Low',
    tagColor: 'light-green',
    priority: 'P3',
    description: 'Low severity — fix when capacity allows.',
  },
};

/**
 * Input for {@link FieldMapper.formatTaskNotes}.
 */
export interface FormatNotesInput {
  testName: string;
  suiteName: string;
  errorMessage: string;
  stackTrace?: string;
  severity: Severity;
  testRunId: string;
  timestamp: Date;
}

/**
 * Maps SemkiEst test-failure data to Asana task fields.
 *
 * Responsibilities:
 * - Resolve severity → tag name, tag colour, priority notation
 * - Build a human-readable task name with priority prefix
 * - Build rich task notes (Asana supports a subset of markdown-like formatting)
 */
export class FieldMapper {
  /**
   * Returns the full severity mapping for the given level.
   */
  getSeverityMapping(severity: Severity): SeverityMapping {
    return SEVERITY_MAPPINGS[severity];
  }

  /**
   * Builds the Asana task name.
   *
   * Format: `[P0] Bug: <testName>`
   */
  formatTaskName(testName: string, severity: Severity): string {
    const { priority } = this.getSeverityMapping(severity);
    return `[${priority}] Bug: ${testName}`;
  }

  /**
   * Builds the full task notes (description) for the Asana task.
   *
   * Includes test metadata, error message, and optionally a stack trace.
   */
  formatTaskNotes(input: FormatNotesInput): string {
    const { tagName, priority, description } = this.getSeverityMapping(
      input.severity,
    );

    const lines: string[] = [
      'Bug Report — Auto-generated by SemkiEst',
      '',
      `Test Suite : ${input.suiteName}`,
      `Test Name  : ${input.testName}`,
      `Severity   : ${input.severity.toUpperCase()} (${priority}) — ${tagName}`,
      `Priority   : ${description}`,
      `Test Run ID: ${input.testRunId}`,
      `Timestamp  : ${input.timestamp.toISOString()}`,
      '',
      '── Error ──────────────────────────────────────────────────────────────',
      '',
      input.errorMessage,
    ];

    if (input.stackTrace) {
      lines.push(
        '',
        '── Stack Trace ────────────────────────────────────────────────────────',
        '',
        input.stackTrace,
      );
    }

    return lines.join('\n');
  }
}
