/**
 * Project report Excel template.
 *
 * Builds a workbook with the following sheets:
 *   1. Summary            — KPI overview and period metadata
 *   2. Run History        — Per-run pass rate and test counts
 *   3. Category Breakdown — Test results split by category
 *   4. Severity Breakdown — Failure counts by severity level
 */
import ExcelJS from 'exceljs';
import type {
  ProjectSummaryReport,
  TestCategory,
  SeverityLevel,
  RunSummary,
  ExcelExportOptions,
} from '../../types/reports';
import { setBorder, formatPercent } from '../excel-export';

// ---------------------------------------------------------------------------
// Colour palette
// ---------------------------------------------------------------------------
const COLORS = {
  titleBg: 'FF1F3864',
  titleFg: 'FFFFFFFF',
  headerBg: 'FF4472C4',
  headerFg: 'FFFFFFFF',
  subheaderBg: 'FFD6E4F7',
  altRowBg: 'FFF2F7FD',
  passed: 'FF70AD47',
  failed: 'FFED7D31',
  skipped: 'FFFFC000',
  border: 'FFBDD7EE',
  improving: 'FF70AD47',
  stable: 'FFFFC000',
  degrading: 'FFED7D31',
  critical: 'FFED2939',
  high: 'FFFF6B35',
  medium: 'FFFFC300',
  low: 'FF52C41A',
  info: 'FF1890FF',
} as const;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build and return a fully populated ExcelJS workbook for a project summary
 * report.
 *
 * @param report  - The project summary data.
 * @param options - Formatting options.
 */
export function buildProjectReportWorkbook(
  report: ProjectSummaryReport,
  options: ExcelExportOptions = {},
): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = options.creator ?? 'SemkiEst Platform';
  workbook.created = new Date();
  workbook.modified = new Date();

  addProjectSummarySheet(workbook, report, options);
  addRunHistorySheet(workbook, report, options);
  addCategoryBreakdownSheet(workbook, report, options);
  addSeverityBreakdownSheet(workbook, report, options);

  return workbook;
}

// ---------------------------------------------------------------------------
// Sheet builders
// ---------------------------------------------------------------------------

function addProjectSummarySheet(
  workbook: ExcelJS.Workbook,
  report: ProjectSummaryReport,
  options: ExcelExportOptions,
): void {
  const sheet = workbook.addWorksheet('Summary', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Project Summary Report`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { width: 30 },
    { width: 24 },
    { width: 16 },
  ];

  // ---- Title ---------------------------------------------------------------
  sheet.mergeCells('A1:C1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = `Project Summary Report — ${report.projectName}`;
  titleCell.font = { bold: true, size: 16, color: { argb: COLORS.titleFg } };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.titleBg } };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  sheet.getRow(1).height = 34;

  // ---- Period subtitle -----------------------------------------------------
  sheet.mergeCells('A2:C2');
  const periodCell = sheet.getCell('A2');
  periodCell.value = `Period: ${report.period.from.toLocaleDateString()} – ${report.period.to.toLocaleDateString()}`;
  periodCell.font = { italic: true, size: 11, color: { argb: '88000000' } };
  periodCell.alignment = { horizontal: 'center' };

  sheet.addRow([]);

  // ---- KPI section ---------------------------------------------------------
  const kpiHeaderRow = sheet.addRow(['Metric', 'Value']);
  kpiHeaderRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { horizontal: 'center' };
    setBorder(cell);
  });

  const { metrics } = report;
  const kpis: [string, string | number | Date][] = [
    ['Project ID', metrics.projectId],
    ['Total Runs (period)', metrics.totalRuns],
    ['Total Tests', metrics.totalTests],
    ['Passed', metrics.passedTests],
    ['Failed', metrics.failedTests],
    ['Average Pass Rate', formatPercent(metrics.avgPassRate)],
    ['Avg Run Duration', formatDuration(metrics.avgDuration)],
    ['Trend', formatTrend(metrics.trend)],
  ];

  if (metrics.lastRunAt) {
    kpis.push(['Last Run', metrics.lastRunAt]);
  }

  kpis.forEach(([label, value], i) => {
    const row = sheet.addRow([label, value instanceof Date ? value : String(value)]);
    row.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg },
      };
      setBorder(cell);
    });
    row.getCell(1).font = { bold: true };

    // Colour pass rate
    if (label === 'Average Pass Rate') {
      row.getCell(2).font = {
        bold: true,
        color: {
          argb: metrics.avgPassRate >= 0.8 ? COLORS.passed : COLORS.failed,
        },
      };
    }

    // Colour trend
    if (label === 'Trend') {
      const trendColor =
        metrics.trend === 'improving'
          ? COLORS.improving
          : metrics.trend === 'degrading'
            ? COLORS.degrading
            : COLORS.stable;
      row.getCell(2).font = { bold: true, color: { argb: trendColor } };
    }

    if (value instanceof Date) {
      row.getCell(2).numFmt = 'yyyy-mm-dd hh:mm:ss';
    }
  });

  sheet.addRow([]);

  // ---- Chart data reference area -------------------------------------------
  // NOTE: ExcelJS does not generate native Excel charts programmatically.
  // This table exposes the data so a spreadsheet user can create charts
  // manually or via a macro / post-processing step.
  const chartDataLabel = sheet.addRow(['Pass/Fail Chart Data']);
  chartDataLabel.getCell(1).font = { bold: true, italic: true, color: { argb: '88000000' } };

  const chartHeaders = sheet.addRow(['Status', 'Count']);
  chartHeaders.eachCell((c) => {
    c.font = { bold: true };
    setBorder(c);
  });

  [
    ['Passed', metrics.passedTests],
    ['Failed', metrics.failedTests],
  ].forEach(([label, count]) => {
    const r = sheet.addRow([label, count]);
    setBorder(r.getCell(1));
    setBorder(r.getCell(2));
  });
}

function addRunHistorySheet(
  workbook: ExcelJS.Workbook,
  report: ProjectSummaryReport,
  options: ExcelExportOptions,
): void {
  const sheet = workbook.addWorksheet('Run History', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Run History`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { header: 'Run ID', width: 36 },
    { header: 'Run Name', width: 34 },
    { header: 'Environment', width: 16 },
    { header: 'Started At', width: 22 },
    { header: 'Total Tests', width: 14 },
    { header: 'Pass Rate', width: 14 },
  ];

  styleHeaderRow(sheet.getRow(1));

  const sorted = [...report.runs].sort(
    (a, b) => b.startedAt.getTime() - a.startedAt.getTime(),
  );

  sorted.forEach((run: RunSummary, i) => {
    const row = sheet.addRow([
      run.id,
      run.name,
      run.environment,
      run.startedAt,
      run.totalTests,
      formatPercent(run.passRate),
    ]);

    const bgColor = i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg;
    row.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
      setBorder(cell);
    });

    row.getCell(4).numFmt = 'yyyy-mm-dd hh:mm';

    const passRateCell = row.getCell(6);
    passRateCell.font = {
      color: { argb: run.passRate >= 0.8 ? COLORS.passed : COLORS.failed },
    };
  });

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };
  sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }];
}

function addCategoryBreakdownSheet(
  workbook: ExcelJS.Workbook,
  report: ProjectSummaryReport,
  options: ExcelExportOptions,
): void {
  const sheet = workbook.addWorksheet('Category Breakdown', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Category Breakdown`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { header: 'Category', width: 20 },
    { header: 'Total', width: 12 },
    { header: 'Passed', width: 12 },
    { header: 'Failed', width: 12 },
    { header: 'Skipped', width: 12 },
    { header: 'Pass Rate', width: 14 },
  ];

  styleHeaderRow(sheet.getRow(1));

  const categoryOrder: TestCategory[] = [
    'ui',
    'functional',
    'visual',
    'performance',
    'accessibility',
    'security',
    'api',
  ];

  categoryOrder.forEach((cat, i) => {
    const breakdown = report.categoryBreakdown[cat];
    if (!breakdown) return;

    const passRate = breakdown.total > 0 ? breakdown.passed / breakdown.total : 0;

    const row = sheet.addRow([
      formatCategoryLabel(cat),
      breakdown.total,
      breakdown.passed,
      breakdown.failed,
      breakdown.skipped,
      formatPercent(passRate),
    ]);

    const bgColor = i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg;
    row.eachCell((cell, colNumber) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
      cell.alignment = { horizontal: 'center' };
      setBorder(cell);
      if (colNumber === 3) cell.font = { color: { argb: COLORS.passed } };
      if (colNumber === 4) cell.font = { color: { argb: COLORS.failed } };
      if (colNumber === 5) cell.font = { color: { argb: COLORS.skipped } };
    });
    row.getCell(1).alignment = { horizontal: 'left' };

    const passRateCell = row.getCell(6);
    passRateCell.font = {
      bold: true,
      color: { argb: passRate >= 0.8 ? COLORS.passed : COLORS.failed },
    };
  });

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };
  sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }];
}

function addSeverityBreakdownSheet(
  workbook: ExcelJS.Workbook,
  report: ProjectSummaryReport,
  options: ExcelExportOptions,
): void {
  const sheet = workbook.addWorksheet('Severity Breakdown', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Severity Breakdown`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { header: 'Severity', width: 16 },
    { header: 'Count', width: 12 },
    { header: '% of Total', width: 14 },
  ];

  styleHeaderRow(sheet.getRow(1));

  const severityOrder: SeverityLevel[] = ['critical', 'high', 'medium', 'low', 'info'];
  const total = severityOrder.reduce(
    (sum, sev) => sum + (report.severityBreakdown[sev] ?? 0),
    0,
  );

  severityOrder.forEach((sev, i) => {
    const count = report.severityBreakdown[sev] ?? 0;
    const pct = total > 0 ? count / total : 0;

    const row = sheet.addRow([
      sev.charAt(0).toUpperCase() + sev.slice(1),
      count,
      formatPercent(pct),
    ]);

    const bgColor = i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg;
    row.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
      cell.alignment = { horizontal: 'center' };
      setBorder(cell);
    });

    row.getCell(1).font = { bold: true, color: { argb: severityColor(sev) } };
    row.getCell(1).alignment = { horizontal: 'left' };
  });

  // Totals row
  const totalsRow = sheet.addRow(['Total', total, formatPercent(1)]);
  totalsRow.eachCell((cell) => {
    cell.font = { bold: true };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.subheaderBg } };
    cell.alignment = { horizontal: 'center' };
    setBorder(cell);
  });
  totalsRow.getCell(1).alignment = { horizontal: 'left' };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function styleHeaderRow(row: ExcelJS.Row): void {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { horizontal: 'center', wrapText: true };
    setBorder(cell);
  });
  row.height = 22;
}

function formatCategoryLabel(category: TestCategory): string {
  const labels: Record<TestCategory, string> = {
    ui: 'UI',
    functional: 'Functional',
    visual: 'Visual',
    performance: 'Performance',
    accessibility: 'Accessibility',
    security: 'Security',
    api: 'API',
  };
  return labels[category];
}

function formatTrend(trend: string): string {
  return trend.charAt(0).toUpperCase() + trend.slice(1);
}

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  if (hours > 0) return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
  if (minutes > 0) return `${minutes}m ${seconds % 60}s`;
  return `${seconds}s`;
}

function severityColor(severity: SeverityLevel): string {
  switch (severity) {
    case 'critical':
      return COLORS.critical;
    case 'high':
      return COLORS.high;
    case 'medium':
      return COLORS.medium;
    case 'low':
      return COLORS.low;
    case 'info':
      return COLORS.info;
  }
}
