/**
 * Run report Excel template.
 *
 * Builds a workbook with the following sheets:
 *   1. Summary          — KPI cards, pass/fail overview, chart data table
 *   2. UI & Functional  — UI + functional test results
 *   3. Visual           — Visual regression test results
 *   4. Performance      — Performance test results with timing data
 *   5. Accessibility    — Accessibility test results with severity
 *   6. Security         — Security test results with severity
 *   7. API              — API test results
 */
import ExcelJS from 'exceljs';
import type { TestRunReport, TestResult, TestCategory, ExcelExportOptions } from '../../types/reports';
import { setBorder, formatPercent } from '../excel-export';

// ---------------------------------------------------------------------------
// Colour palette
// ---------------------------------------------------------------------------
const COLORS = {
  titleBg: 'FF1F3864',
  titleFg: 'FFFFFFFF',
  headerBg: 'FF4472C4',
  headerFg: 'FFFFFFFF',
  subheaderBg: 'FFD6E4F7',
  altRowBg: 'FFF2F7FD',
  passed: 'FF70AD47',
  failed: 'FFED7D31',
  skipped: 'FFFFC000',
  error: 'FFE74C3C',
  border: 'FFBDD7EE',
  critical: 'FFED2939',
  high: 'FFFF6B35',
  medium: 'FFFFC300',
  low: 'FF52C41A',
  info: 'FF1890FF',
} as const;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build and return a fully populated ExcelJS workbook for a test run report.
 *
 * The workbook is *not* written to any stream here — callers use
 * `streamWorkbookToResponse` (or `workbook.xlsx.writeBuffer`) after this.
 *
 * @param report  - The test run data.
 * @param options - Formatting options.
 */
export function buildRunReportWorkbook(
  report: TestRunReport,
  options: ExcelExportOptions = {},
): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = options.creator ?? 'SemkiEst Platform';
  workbook.created = new Date();
  workbook.modified = new Date();

  addSummarySheet(workbook, report, options);
  addCategorySheet(workbook, report, ['ui', 'functional'], 'UI & Functional', options);
  addCategorySheet(workbook, report, ['visual'], 'Visual', options);
  addPerformanceSheet(workbook, report, options);
  addCategorySheet(workbook, report, ['accessibility'], 'Accessibility', options);
  addCategorySheet(workbook, report, ['security'], 'Security', options);
  addCategorySheet(workbook, report, ['api'], 'API', options);

  return workbook;
}

// ---------------------------------------------------------------------------
// Sheet builders
// ---------------------------------------------------------------------------

function addSummarySheet(
  workbook: ExcelJS.Workbook,
  report: TestRunReport,
  options: ExcelExportOptions,
): void {
  const sheet = workbook.addWorksheet('Summary', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Test Run Report`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { width: 28 },
    { width: 22 },
    { width: 16 },
    { width: 16 },
    { width: 16 },
  ];

  // ---- Title ---------------------------------------------------------------
  sheet.mergeCells('A1:E1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = `Test Run Report — ${report.runName}`;
  titleCell.font = { bold: true, size: 16, color: { argb: COLORS.titleFg } };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.titleBg } };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  sheet.getRow(1).height = 34;

  // ---- Metadata block ------------------------------------------------------
  const metaRows: [string, string | number | Date][] = [
    ['Project', report.projectName],
    ['Environment', report.environment],
    ['Run ID', report.id],
    ['Started', report.startedAt],
    ['Completed', report.completedAt],
    [
      'Duration',
      formatDuration(report.completedAt.getTime() - report.startedAt.getTime()),
    ],
  ];

  metaRows.forEach(([label, value]) => {
    const row = sheet.addRow([label, value]);
    row.getCell(1).font = { bold: true };
    if (value instanceof Date) {
      row.getCell(2).numFmt = 'yyyy-mm-dd hh:mm:ss';
    }
  });

  sheet.addRow([]);

  // ---- KPI header ----------------------------------------------------------
  const kpiHeader = sheet.addRow(['Metric', 'Total', 'Passed', 'Failed', 'Skipped']);
  kpiHeader.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { horizontal: 'center' };
    setBorder(cell);
  });

  // ---- KPI data row --------------------------------------------------------
  const kpiRow = sheet.addRow([
    'All Tests',
    report.totalTests,
    report.passedTests,
    report.failedTests,
    report.skippedTests,
  ]);
  kpiRow.eachCell((cell, colNumber) => {
    setBorder(cell);
    cell.alignment = { horizontal: 'center' };
    if (colNumber === 3) cell.font = { color: { argb: COLORS.passed } };
    if (colNumber === 4) cell.font = { color: { argb: COLORS.failed } };
    if (colNumber === 5) cell.font = { color: { argb: COLORS.skipped } };
  });

  // Pass rate
  const passRate = report.totalTests > 0 ? report.passedTests / report.totalTests : 0;
  const passRateRow = sheet.addRow(['Pass Rate', formatPercent(passRate)]);
  passRateRow.getCell(1).font = { bold: true };
  passRateRow.getCell(2).font = {
    bold: true,
    color: { argb: passRate >= 0.8 ? COLORS.passed : COLORS.failed },
  };

  sheet.addRow([]);

  // ---- Category breakdown section ------------------------------------------
  const catHeader = sheet.addRow(['Category', 'Total', 'Passed', 'Failed', 'Skipped']);
  catHeader.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { horizontal: 'center' };
    setBorder(cell);
  });

  const categoryTotals = getCategoryTotals(report.results);
  Object.entries(categoryTotals).forEach(([cat, counts], i) => {
    const row = sheet.addRow([
      formatCategoryLabel(cat as TestCategory),
      counts.total,
      counts.passed,
      counts.failed,
      counts.skipped,
    ]);
    row.eachCell((cell, colNumber) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg },
      };
      cell.alignment = { horizontal: 'center' };
      setBorder(cell);
      if (colNumber === 3) cell.font = { color: { argb: COLORS.passed } };
      if (colNumber === 4) cell.font = { color: { argb: COLORS.failed } };
      if (colNumber === 5) cell.font = { color: { argb: COLORS.skipped } };
    });
    row.getCell(1).alignment = { horizontal: 'left' };
  });

  // ---- Visual data table for pass/fail chart (chart data reference area) ---
  // NOTE: ExcelJS does not generate native Excel charts programmatically.
  // This data table is positioned so a macro or post-processing step can bind
  // a chart to it.  The section is labelled for clarity.
  sheet.addRow([]);
  const chartDataHeader = sheet.addRow(['Pass/Fail Chart Data', '', '', '', '']);
  chartDataHeader.getCell(1).font = { bold: true, italic: true, color: { argb: '88000000' } };

  const chartLabelRow = sheet.addRow(['Status', 'Count']);
  chartLabelRow.eachCell((c) => {
    c.font = { bold: true };
    setBorder(c);
  });
  [
    ['Passed', report.passedTests],
    ['Failed', report.failedTests],
    ['Skipped', report.skippedTests],
  ].forEach(([label, count]) => {
    const row = sheet.addRow([label, count]);
    setBorder(row.getCell(1));
    setBorder(row.getCell(2));
  });
}

/**
 * Generic per-category result sheet builder.
 *
 * @param categories - The test categories to include in this sheet.
 * @param sheetName  - The worksheet tab name.
 */
function addCategorySheet(
  workbook: ExcelJS.Workbook,
  report: TestRunReport,
  categories: TestCategory[],
  sheetName: string,
  options: ExcelExportOptions,
): void {
  const results = report.results.filter((r) => categories.includes(r.category));

  const sheet = workbook.addWorksheet(sheetName, {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — ${sheetName}`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { header: 'Test Name', width: 40 },
    { header: 'Category', width: 16 },
    { header: 'Status', width: 12 },
    { header: 'Duration (ms)', width: 16 },
    { header: 'Severity', width: 12 },
    { header: 'URL', width: 40 },
    { header: 'Error', width: 50 },
  ];

  styleHeaderRow(sheet.getRow(1));

  results.forEach((result, i) => {
    const row = sheet.addRow([
      result.name,
      formatCategoryLabel(result.category),
      result.status.charAt(0).toUpperCase() + result.status.slice(1),
      result.duration,
      result.severity ?? '',
      result.url ?? '',
      result.error ?? '',
    ]);

    const bgColor = i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg;
    row.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
      setBorder(cell);
    });

    // Status colour
    const statusCell = row.getCell(3);
    statusCell.font = {
      color: { argb: statusColor(result.status) },
      bold: result.status === 'failed' || result.status === 'error',
    };

    // Severity colour
    if (result.severity) {
      row.getCell(5).font = { color: { argb: severityColor(result.severity) } };
    }
  });

  // Auto-filter
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };

  // Freeze header row
  sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }];

  addResultSummaryFooter(sheet, results);
}

/**
 * Performance sheet with additional timing metrics columns.
 */
function addPerformanceSheet(
  workbook: ExcelJS.Workbook,
  report: TestRunReport,
  options: ExcelExportOptions,
): void {
  const results = report.results.filter((r) => r.category === 'performance');
  const sheet = workbook.addWorksheet('Performance', {
    pageSetup: options.includePrintLayout
      ? { fitToPage: true, fitToWidth: 1, orientation: 'landscape' }
      : undefined,
  });

  if (options.includePrintLayout) {
    sheet.headerFooter.oddHeader = `&C&B${report.projectName} — Performance`;
    sheet.headerFooter.oddFooter = '&LGenerated by SemkiEst&R&P of &N';
  }

  sheet.columns = [
    { header: 'Test Name', width: 40 },
    { header: 'Status', width: 12 },
    { header: 'Duration (ms)', width: 16 },
    { header: 'Duration (s)', width: 14 },
    { header: 'URL', width: 40 },
    { header: 'Severity', width: 12 },
    { header: 'Error', width: 50 },
  ];

  styleHeaderRow(sheet.getRow(1));

  // Performance thresholds for conditional colouring (simple heuristic).
  const PERF_SLOW_MS = 3000;
  const PERF_VERY_SLOW_MS = 8000;

  results.forEach((result, i) => {
    const row = sheet.addRow([
      result.name,
      result.status.charAt(0).toUpperCase() + result.status.slice(1),
      result.duration,
      (result.duration / 1000).toFixed(2),
      result.url ?? '',
      result.severity ?? '',
      result.error ?? '',
    ]);

    const bgColor = i % 2 === 0 ? 'FFFFFFFF' : COLORS.altRowBg;
    row.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
      setBorder(cell);
    });

    // Status colour
    row.getCell(2).font = { color: { argb: statusColor(result.status) } };

    // Duration colour — highlight slow tests
    const durationCell = row.getCell(3);
    if (result.duration >= PERF_VERY_SLOW_MS) {
      durationCell.font = { color: { argb: COLORS.failed }, bold: true };
    } else if (result.duration >= PERF_SLOW_MS) {
      durationCell.font = { color: { argb: COLORS.skipped } };
    } else {
      durationCell.font = { color: { argb: COLORS.passed } };
    }
  });

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };
  sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }];

  addResultSummaryFooter(sheet, results);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function styleHeaderRow(row: ExcelJS.Row): void {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { horizontal: 'center', wrapText: true };
    setBorder(cell);
  });
  row.height = 22;
}

function addResultSummaryFooter(sheet: ExcelJS.Worksheet, results: TestResult[]): void {
  if (results.length === 0) return;

  const lastRow = sheet.lastRow?.number ?? 1;
  sheet.addRow([]);

  const passed = results.filter((r) => r.status === 'passed').length;
  const failed = results.filter((r) => r.status === 'failed' || r.status === 'error').length;
  const skipped = results.filter((r) => r.status === 'skipped').length;
  const total = results.length;

  const summaryHeaderRow = sheet.addRow(['Summary', 'Total', 'Passed', 'Failed', 'Skipped']);
  summaryHeaderRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.subheaderBg } };
    setBorder(cell);
  });
  summaryHeaderRow.getCell(1).font = { bold: true };

  const summaryDataRow = sheet.addRow(['This Sheet', total, passed, failed, skipped]);
  summaryDataRow.eachCell((cell, colNumber) => {
    setBorder(cell);
    cell.alignment = { horizontal: 'center' };
    if (colNumber === 3) cell.font = { color: { argb: COLORS.passed } };
    if (colNumber === 4) cell.font = { color: { argb: COLORS.failed } };
    if (colNumber === 5) cell.font = { color: { argb: COLORS.skipped } };
  });

  // Suppress "unused variable" — lastRow used for intent documentation only
  void lastRow;
}

/** Map a TestCategory value to a human-readable label. */
function formatCategoryLabel(category: TestCategory): string {
  const labels: Record<TestCategory, string> = {
    ui: 'UI',
    functional: 'Functional',
    visual: 'Visual',
    performance: 'Performance',
    accessibility: 'Accessibility',
    security: 'Security',
    api: 'API',
  };
  return labels[category];
}

/** Return the ARGB colour string for a given test status. */
function statusColor(status: string): string {
  switch (status) {
    case 'passed':
      return COLORS.passed;
    case 'failed':
    case 'error':
      return COLORS.failed;
    case 'skipped':
      return COLORS.skipped;
    default:
      return '88000000';
  }
}

/** Return the ARGB colour string for a given severity level. */
function severityColor(severity: string): string {
  switch (severity) {
    case 'critical':
      return COLORS.critical;
    case 'high':
      return COLORS.high;
    case 'medium':
      return COLORS.medium;
    case 'low':
      return COLORS.low;
    case 'info':
      return COLORS.info;
    default:
      return '88000000';
  }
}

/** Format a millisecond duration as a human-readable string. */
function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  if (hours > 0) return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
  if (minutes > 0) return `${minutes}m ${seconds % 60}s`;
  return `${seconds}s`;
}

/** Compute totals per category from a result array. */
function getCategoryTotals(
  results: TestResult[],
): Record<string, { total: number; passed: number; failed: number; skipped: number }> {
  const categories: TestCategory[] = [
    'ui',
    'functional',
    'visual',
    'performance',
    'accessibility',
    'security',
    'api',
  ];

  return Object.fromEntries(
    categories.map((cat) => {
      const filtered = results.filter((r) => r.category === cat);
      return [
        cat,
        {
          total: filtered.length,
          passed: filtered.filter((r) => r.status === 'passed').length,
          failed: filtered.filter((r) => r.status === 'failed' || r.status === 'error').length,
          skipped: filtered.filter((r) => r.status === 'skipped').length,
        },
      ];
    }),
  );
}
