/**
 * Builds formatted Markdown content for SemkiEst test result PR comments.
 *
 * Produces human-readable summaries suitable for GitHub Pull Request comments,
 * including pass/fail counts, pass rate, duration, and a link to the full report.
 */

import type { TestRunResult, TestRunSummary } from './types.js';

/**
 * Builds a formatted Markdown comment summarizing a completed SemkiEst test run.
 *
 * The comment includes:
 * - Run ID and project metadata
 * - Summary table (passed/failed/skipped/total/pass rate/duration)
 * - Error message excerpt (if the run failed with a top-level error)
 * - Link to the full report
 *
 * @param result - The completed test run result from the SemkiEst API
 * @returns Markdown string suitable for posting as a GitHub PR comment
 */
export function buildTestSummaryComment(result: TestRunResult): string {
  const isSuccess = result.status === 'passed';
  const statusIcon = isSuccess ? ':white_check_mark:' : ':x:';
  const statusLabel = isSuccess ? 'Tests Passed' : 'Tests Failed';

  const lines: string[] = [
    `## :microscope: SemkiEst Test Results \u2014 ${statusIcon} ${statusLabel}`,
    '',
    `**Run ID:** \`${result.runId}\``,
    `**Project:** \`${result.projectId}\``,
  ];

  if (result.testProfile) {
    lines.push(`**Profile:** \`${result.testProfile}\``);
  }

  lines.push('');

  if (result.summary) {
    lines.push(...buildSummaryTable(result.summary));
    lines.push('');
  }

  if (result.summary?.errorMessage) {
    lines.push('### Error Details');
    lines.push('');
    lines.push('```');
    lines.push(result.summary.errorMessage);
    lines.push('```');
    lines.push('');
  }

  if (result.reportUrl) {
    lines.push(`[:microscope: View Full Report](${result.reportUrl})`);
    lines.push('');
  }

  const timestamp = formatTimestamp(result.completedAt ?? result.createdAt);
  lines.push(
    `<sub>Generated by [SemkiEst](https://semkiest.io) at ${timestamp}</sub>`,
  );

  return lines.join('\n');
}

/**
 * Builds a Markdown comment for a test run that ended unexpectedly
 * (cancelled, timed out, or API error).
 *
 * @param runId - The test run ID
 * @param status - The terminal status ('cancelled' | 'timeout' | 'error')
 * @param errorMessage - Optional error details
 * @returns Markdown string
 */
export function buildErrorComment(
  runId: string,
  status: 'cancelled' | 'timeout' | 'error',
  errorMessage?: string,
): string {
  const statusMessages: Record<string, string> = {
    cancelled: ':warning: Test Run Cancelled',
    timeout: ':hourglass: Test Run Timed Out',
    error: ':x: Test Run Error',
  };

  const title = statusMessages[status] ?? ':x: Test Run Failed';

  const lines: string[] = [
    `## :microscope: SemkiEst Test Results \u2014 ${title}`,
    '',
    `**Run ID:** \`${runId}\``,
    '',
  ];

  if (errorMessage) {
    lines.push('### Details');
    lines.push('');
    lines.push('```');
    lines.push(errorMessage);
    lines.push('```');
    lines.push('');
  }

  const timestamp = formatTimestamp(new Date().toISOString());
  lines.push(
    `<sub>Generated by [SemkiEst](https://semkiest.io) at ${timestamp}</sub>`,
  );

  return lines.join('\n');
}

/** Builds the summary statistics table rows. */
function buildSummaryTable(summary: TestRunSummary): string[] {
  const passRate =
    summary.total > 0
      ? Math.round((summary.passed / summary.total) * 100)
      : 0;
  const duration = formatDuration(summary.durationMs);

  return [
    '### Summary',
    '',
    '| Metric | Value |',
    '|:-------|------:|',
    `| :white_check_mark: Passed | **${summary.passed}** |`,
    `| :x: Failed | **${summary.failed}** |`,
    `| :next_track_button: Skipped | **${summary.skipped}** |`,
    `| Total | **${summary.total}** |`,
    `| Pass Rate | **${passRate}%** |`,
    `| Duration | **${duration}** |`,
  ];
}

/** Formats milliseconds into a human-readable duration string. */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const minutes = Math.floor(ms / 60_000);
  const seconds = Math.round((ms % 60_000) / 1000);
  return `${minutes}m ${seconds}s`;
}

/** Formats an ISO 8601 timestamp to a human-readable UTC string. */
function formatTimestamp(isoString: string): string {
  try {
    return new Date(isoString).toUTCString();
  } catch {
    return isoString;
  }
}
