# =============================================================================
# SemkiEst Platform – AWS Secrets Manager
# =============================================================================
# Centralised secrets store for all runtime credentials.
# Secrets are initially populated with placeholder values; real values must be
# injected via CI/CD pipeline or manually via the AWS console / CLI.
# =============================================================================

# -----------------------------------------------------------------------------
# Application secrets (DATABASE_URL, REDIS_URL, JWT_SECRET, etc.)
# -----------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "app" {
  name                    = "${local.name_prefix}/app"
  description             = "Runtime application secrets for ${local.name_prefix}"
  recovery_window_in_days = var.secrets_recovery_window_days

  tags = {
    Name = "${local.name_prefix}-app-secrets"
  }
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id

  # Initial placeholder values.
  # Update these via CI/CD or:
  #   aws secretsmanager put-secret-value \
  #     --secret-id <secret-arn> \
  #     --secret-string '{"DATABASE_URL":"postgresql://...",...}'
  secret_string = jsonencode({
    DATABASE_URL  = "REPLACE_ME"
    REDIS_URL     = "REPLACE_ME"
    JWT_SECRET    = "REPLACE_ME_32chars_minimum_change_this"
    INTERNAL_API_KEY = "REPLACE_ME"
  })

  lifecycle {
    # Prevent Terraform from overwriting secrets that have been updated outside IaC
    ignore_changes = [secret_string]
  }
}

# -----------------------------------------------------------------------------
# RDS credentials (auto-generated by rds.tf, stored here for reference)
# -----------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "rds" {
  name                    = "${local.name_prefix}/rds"
  description             = "RDS master credentials for ${local.name_prefix}"
  recovery_window_in_days = var.secrets_recovery_window_days

  tags = {
    Name = "${local.name_prefix}-rds-secrets"
  }
}

resource "aws_secretsmanager_secret_version" "rds" {
  secret_id = aws_secretsmanager_secret.rds.id

  secret_string = jsonencode({
    username = aws_db_instance.main.username
    password = random_password.rds_master.result
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = aws_db_instance.main.db_name
    url      = "postgresql://${aws_db_instance.main.username}:${random_password.rds_master.result}@${aws_db_instance.main.address}:${aws_db_instance.main.port}/${aws_db_instance.main.db_name}?schema=public"
  })
}

# -----------------------------------------------------------------------------
# Redis auth token
# -----------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "redis" {
  name                    = "${local.name_prefix}/redis"
  description             = "Redis auth token for ${local.name_prefix}"
  recovery_window_in_days = var.secrets_recovery_window_days

  tags = {
    Name = "${local.name_prefix}-redis-secrets"
  }
}

resource "aws_secretsmanager_secret_version" "redis" {
  secret_id = aws_secretsmanager_secret.redis.id

  secret_string = jsonencode({
    auth_token = random_password.redis_auth.result
    host       = aws_elasticache_cluster.main.cache_nodes[0].address
    port       = aws_elasticache_cluster.main.cache_nodes[0].port
    url        = "redis://:${random_password.redis_auth.result}@${aws_elasticache_cluster.main.cache_nodes[0].address}:${aws_elasticache_cluster.main.cache_nodes[0].port}"
  })
}
